### ISSUE TITLE
Without Discrete columns the Loss increase strongly

### ISSUE THREAD

**Issue by tomaskappa** [sdv-dev/CTGAN#46] opened 2020-05-06 15:19 UTC
### Description

I have fitted the Synthesizer with the same dataset several times, making litle changes.
Always, all the epochs have had losses (Loss G & Loss D) under |4|. None of the maximum numbers passed that threshold. And, in 300 epoch I usually get less than 0.8 . 
But when I train the model without the only discrete column that I have in my dataset, both losses increase very much. The Loss G peaked at -95 in epoch 43. For other hand, the loss D peaked at -2333 in epoch 37, and it scored -9 in epoch 300

### What I Did

I created a discrete column with only one label, and the losses decreses to the normal numbers.
Do you know what could have happened? Why the losses are increasing in that way when I take out the only discrete column?

![image](https://user-images.githubusercontent.com/59977750/81195040-b5209f80-8f93-11ea-965d-241bdddf89d2.png)
![image](https://user-images.githubusercontent.com/59977750/81195072-bf429e00-8f93-11ea-96a9-d6c0ccd9a585.png)

**Comment by Aditya-Agarwal-018** [comment] 2020-12-22 17:19
How to run the code without any discrete_columns?

I am trying with : 
------------------CODE--------------------------------
# Names of the columns that are discrete
discrete_columns = None

ctgan = CTGANSynthesizer(epochs=10)
ctgan.fit(data, discrete_columns)
------------------CODE--------------------------------

But I get an error:

----> 2 ctgan.fit(df_all)

~\.conda\envs\py3_jupyter\lib\site-packages\ctgan\synthesizers\ctgan.py in fit(self, train_data, discrete_columns, epochs)
    249         train_data = self._transformer.transform(train_data)
    250 
--> 251         self._data_sampler = DataSampler(
    252             train_data,
    253             self._transformer.output_info_list,

~\.conda\envs\py3_jupyter\lib\site-packages\ctgan\data_sampler.py in __init__(self, data, output_info, log_frequency)
     40 
     41         # Prepare an interval matrix for efficiently sample conditional vector
---> 42         max_category = max(
     43             [column_info[0].dim for column_info in output_info
     44              if is_discrete_column(column_info)])

ValueError: max() arg is an empty sequence

**Comment by fealho** [comment] 2020-12-22 18:14
Hi @Aditya-Agarwal-018, this seems to be a different topic, would you mind opening a new issue?

**Comment by csala** [comment] 2021-03-22 11:14
As explained [in this SDV issue](https://github.com/sdv-dev/SDV/issues/336#issuecomment-797004358), the loss ranges on their own are no indicative of good or bad training outcomes, so no conclusions can be reached unless the quality of the generated data is [evaluated using external metrics](https://sdv.dev/SDV/user_guides/evaluation/evaluation_framework.html).

This issue is also old and probably outdated, so I'm closing it for now. Please feel free to reopen it if the problem can still be reproduced and an impact on the output quality can be observed.

**Closed by csala** 2021-03-22 11:14 UTC
Labels: question
