### ISSUE TITLE
ValueError: cannot reshape array of size 20 into shape (1,10)   when ctgan.fit(dataframe, discrete_columns[0:1], epochs = 5) is called

### ISSUE THREAD

**Issue by nisarkhanatwork** [sdv-dev/CTGAN#93] opened 2020-11-21 10:15 UTC
* CTGAN version:0.2.2    
* Python version:Python 3.6.12 :: Anaconda, Inc.
* Operating System: ubuntu

### Description
I got error when the fit function is called for a single column. Please let me know whether I am doing something wrong.
## Describe what you were trying to get done.
from ctgan import CTGANSynthesizer
ctgan = CTGANSynthesizer()
ctgan.fit(dataframe, discrete_columns[0:1], epochs = 5)

## Tell us what happened, what went wrong, and what you expected to happen.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-399bd7dadd5a> in <module>
----> 1 ctgan.fit(dataframe, discrete_columns[0:1], epochs = 5)

~/anaconda3/envs/genome/lib/python3.6/site-packages/ctgan/synthesizer.py in fit(self, train_data, discrete_columns, epochs, log_frequency)
    153             self.transformer = DataTransformer()
    154             self.transformer.fit(train_data, discrete_columns)
--> 155         train_data = self.transformer.transform(train_data)
    156 
    157         data_sampler = Sampler(train_data, self.transformer.output_info)

~/anaconda3/envs/genome/lib/python3.6/site-packages/ctgan/transformer.py in transform(self, data)
    123             column_data = data[[meta['name']]].values
    124             if 'model' in meta:
--> 125                 values += self._transform_continuous(meta, column_data)
    126             else:
    127                 values.append(self._transform_discrete(meta, column_data))

~/anaconda3/envs/genome/lib/python3.6/site-packages/ctgan/transformer.py in _transform_continuous(self, column_meta, data)
     87         model = column_meta['model']
     88 
---> 89         means = model.means_.reshape((1, self.n_clusters))
     90         stds = np.sqrt(model.covariances_).reshape((1, self.n_clusters))
     91         features = (data - means) / (4 * stds)

ValueError: cannot reshape array of size 20 into shape (1,10)

**Comment by fealho** [comment] 2020-11-25 18:16
Hi @abhisheknagar1983 would you mind providing a small hand crafted example, so that we can reproduce the issue? Some additional context, such as what the dataframe and discrete_columns variables contain, will make it easier for us to help you.

**Comment by nisarkhanatwork** [comment] 2020-11-25 18:22
> Hi @abhisheknagar1983 would you mind providing a small hand crafted example, so that we can reproduce the issue? Some additional context, such as what the dataframe and discrete_columns variables contain, will make it easier for us to help you.

Hi,
Thank you for replying. Here is my colab notebook:

https://colab.research.google.com/drive/1Imuu8YiVKDIFWunu9dGW4xHFvGWuTWR2?usp=sharing

Thank you.
Nisar

**Comment by fealho** [comment] 2020-11-25 18:41
We're having some trouble accessing the data files since they're on your private google drive (/content/drive/MyDrive/riya_proj1/), would it be possible for you to provide access either here or privately via email?

**Comment by fealho** [comment] 2020-11-25 18:46
Also, your comment above seems to suggest that you're trying to model a single column; however, your code seems to actually be modeling all ~16k columns. The only difference is that all but one of them (i.e. all of the columns except TSPAN6) are being modeled as continuous values whereas TSPAN6 is modeled as a discrete column. I'm not sure if this was intentional?

**Comment by nisarkhanatwork** [comment] 2020-11-25 18:49
> I'm having some trouble accessing the data files since they're on your private google drive (/content/drive/MyDrive/riya_proj1/), would it be possible for you to provide access either here or privately via email?

Sorry. Here is the link to the data :+1: 
 
https://drive.google.com/drive/folders/1TWkmk4VYIu8cE1thXdkqXmAejVZNNBea?usp=sharing

**Comment by nisarkhanatwork** [comment] 2020-11-25 18:59
> Also, your comment above seems to suggest that you're trying to model a single column; however, your code seems to actually be modeling all ~16k columns. The only difference is that all but one of them (i.e. all of the columns except TSPAN6) are being modeled as continuous values whereas TSPAN6 is modeled as a discrete column. I'm not sure if this was intentional?

I want to model based on all columns, but it gave other problem which I am discussing in #95 
By continuous, you mean they are not integers ? I want all columns to be integers.
What I understood is, if I give a set of columns as parameters(eg: discrete_columns[0:10]) it will create samples for that columns only.
And by specifying less number of columns in fit, I thought I will take less memory...

**Comment by fealho** [comment] 2020-11-25 20:50
It appears your dataframe has multiple columns with the same name. To verify this, you can run:

```python3
from collections import Counter
for k, v in Counter(exprT.columns).items():
    if v > 1:
        print(k, v)
```

The list of duplicated columns is:

```
from collections import Counter
for k, v in Counter(exprT.columns).items():
    if v > 1:
        print(k, v)
```

These columns cause the error. Can you try renaming the duplicated columns and check that it works?

**Comment by nisarkhanatwork** [comment] 2020-11-27 03:09
Hi @fealho @csala , 
Thank you.
So, large number of columns ~16k is not a problem for CTGAN.
It worked amazingly in my laptop which has got only 8GB RAM. But I got negative integers as some of the values.
As I have very few rows I have to consider #95...

**Comment by csala** [comment] 2020-11-27 14:36
Great! Good to hear @nisarkhanatwork 

In order to handle the negative values problem, please have a look at the [CopulaGAN model in SDV](https://sdv.dev/SDV/user_guides/single_table/copulagan.html), which adds a distribution transformation layer on top of CTGAN that covers this problem.

I'm closing the issue for now, as the original problem seems to be resolved.

**Closed by csala** 2020-11-27 14:36 UTC
