### ISSUE TITLE
Unstable Output

### ISSUE THREAD

**Issue by nabarunaguha** [sdv-dev/CTGAN#1] opened 2019-09-29 23:42 UTC
* Python version: 3.7.3
* TensorFlow version: 1.14.0

Hi! I am intrigued to work with CTGAN as the purpose of CTGAN exactly matches my goal. 

My Dataset has 1846 columns (All continuous) with each column following different distribution and also exhibiting correlations among each other.

I want to expand my dataset (3000 -> 20,000+ samples) so that the new generated dataset follows the same distributions as in the original and in turn also preserves the correlations among the columns.

I am facing the following issues, implementing CTGAN on my dataset:

1. It runs only below 50 columns, with columns taken more than that, it generates output with only nan.
2. The outputs are not repetitive/stable, by this I mean, I get result for 50 or less columns in one run and next when I run the model with same data again, I get output as only nan.
3. In the documentation, there is flag for model path but the model doesn't get saved, also makes sense because I couldn't find any sourcecode using that flag. 

I will be grateful if I am given some leads regarding the issues I am facing.

Thanks and kind regards,
Nabaruna

**Comment by ssierral** [comment] 2020-03-27 01:38
Can you share a sample of your dataset?
Have you been able to solve your problem?

**Comment by csala** [comment] 2020-06-22 14:34
Closing this issue because the code has gone through a few changes since the issue was open and there is no data to try to reproduce the indicated problems.

Please feel free to open again if there are any follow up comments.

**Closed by csala** 2020-06-22 14:34 UTC
