### ISSUE TITLE
Ability to provide user-defined callback function to CTGANSyntesizer

### ISSUE THREAD

**Issue by PJPRoche** [sdv-dev/CTGAN#256] opened 2022-11-24 14:39 UTC
### Problem Description

Only in verbose model can you see Generator and Discriminator loss metrics at the end of each epoch. This is useful for a basic visual confirmation that the model is running but does not allow for detailed quantitative inspection of the model as it is training. 

### Expected behavior

It would be helpful if the user could supply a function, for example passed to the CTGANSynthesizer class when instantiated, that would then be called at the end of each epoch. Ideally, from your callback, you would want to call something like the sample function at the end of each epoch to obtain synthetic data and then subject this synthetic data to some of the SD Metrics. But with sample being a member function of the CTGANSynthesizer class this is arguably a bit awkward.

**Comment by npatki** [comment] 2022-11-29 00:24
Hi @PJPRoche, thanks for filing. The idea makes sense to me, and I agree we'd have to think more about the workflow and API part.

I believe we have an existing issue about callbacks here: https://github.com/sdv-dev/SDV/issues/460

This would involve a larger refactor of the existing CTGAN model, so we haven't been able to add it to our roadmap yet. But every new issue, use case and request that we hear about helps us prioritize! I'll mark this as a duplicate of the issue linked above -- feel free to add your use case and requirements to it.

**Closed by npatki** 2022-11-29 00:24 UTC
Labels: new feature, pending review
